app:
  name: gaDataPartnersHistoricaldata

etlOptions:
  source:
    plugin: googleanalyticsjobs
    maxRetries: 3
    timeoutMillis: 5000
  transformer:
    plugin: simplecopy
    minSuccessPercentage: 1
    timeoutMillis: 5000
  destination:
    plugin: csvfile
    maxRetries: 3
    timeoutMillis: 5000
    batchSize: 1

sources:
  adwordsreportshistoricaldata:
    accountsList:
      - name:	HI:Category
        id: 531-703-1064
    reportQuery: "SELECT AccountDescriptiveName, CampaignName, AdGroupName, Criteria, KeywordMatchType, IsNegative, Impressions, Clicks, Conversions, Cost FROM KEYWORDS_PERFORMANCE_REPORT WHERE Impressions > 0 and CampaignName = 'Painters:12|NA:NA' "

destinations:
  csvfile:
    directory: /Users/techdev3/src/inceptum-etl/tmp/asteroids
    fileName: painters_new-
    cleanUpDirectory : false

savepoints:
  static:
    savepoint: '{"startDate":"20170921","endDate":"20170921","paceAmount":1,"paceTime":"years","finalDate":"20160921","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'
