app:
  name: Inceptum Etl
  context:
    - adwordsKeywords
    - adwordsClicks

logging:
  streams:
    console:
      type: console
    myredis:
      type: redis
    mainLogFile:
      type: file
      path: main.log
  loggers:
    - name: ROOT
      streams:
        console: debug
    - name: ioc/
      streams:
        console: debug
    - name: mysql/
      streams:
        console: debug

sources:
  adwords:
    adwordsClicks:
      maxRetries: 5000
      timeoutMillis: 1
      account: THE_ACCOUNT_NAME
      token: DEVELOPER_TOKEN
      userAgent: YOUR_PROJECT_NAME
      clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
      clientId: ADWORDS_API_CLIENT_ID
      clientSecret: ADWORDS_API_CLIENT_SECRET
      refreshToken: ADWORDS_API_REFRESHTOKEN
      version: v201705
      accountsList:
        - name: ADWORDS_ACOUNT_NAME
          id: ADWORDS_ACOUNT_ID	

transformers:
  splitadwords:
    adwordsKeywords:
      minSuccessPercentage: 1
      timeoutMillis: 5000
    adwordsClicks:
      minSuccessPercentage: 1
      timeoutMillis: 5000
  simplecopy:
    adwordsKeywords:
      minSuccessPercentage: 1
      timeoutMillis: 5000
    adwordsClicks:
      minSuccessPercentage: 1
      timeoutMillis: 5000

destinations:
  csvfile:
    adwordsKeywords:
      timeoutMillis: 5000
      batchSize: 1
      directory: /Users/techdev3/src/hip-etls/files
      fileName: akp
    adwordsClicks:
      timeoutMillis: 5000
      batchSize: 1
      directory: /Users/techdev3/src/hip-etls/files
      fileName: acp
  jsonfile:
    adwordsKeywords:
      timeoutMillis: 5000
      batchSize: 1
      directory: /Users/techdev3/src/hip-etls/files
      fileName: akp
    adwordsClicks:
      timeoutMillis: 5000
      batchSize: 1
      directory: /Users/techdev3/src/hip-etls/files
      fileName: acp
  s3bucket:
    adwordsKeywords: 
      timeoutMillis: 5000
      batchSize: 1
      fileType: csv
      bucket: test/fact_keywords_performance
      directory: /Users/techdev3/src/hip-etls/files
      fileName: acp
    adwordsClicks: 
      timeoutMillis: 5000
      batchSize: 1
      fileType: csv
      bucket: test/fact_click_performance
      directory: /Users/techdev3/src/hip-etls/files
      fileName: acp
  redshift:
    adwordsKeywords: 
      timeoutMillis: 5000
      batchSize: 1
      bucket: s3://path
      tempDirectory:  /Users/techdev3/src/hip-etls/files
      tableCopyName: copy.fact_keywords_performance
      tableName: public.fact_keywords_performance
      bulkDeleteMatchFields: 
        - account 
        - report_date
    adwordsClicks: 
      timeoutMillis: 5000
      batchSize: 1
      bucket: s3://path
      tableCopyName: copy.fact_keywords_performance
      tableName: public.fact_keywords_performance
      bulkDeleteMatchFields: 
        - account 
        - report_date

mysql:
  savePoint: # this is the name of the object that will be exposed in the context
    master:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
    slave:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10

postgres:
  redshift:
    master:
      user: postgres
      database: hipages
      password: password
      port: 5432
      host: localhost
      max: 5
      min: 1
      refreshIdle: true
      idleTimeoutMillis: 20000
      # reapIntervalMillis: number;
      # returnToHead?: boolean;
      application_name: test
      # Promise?: PromiseConstructorLik
    slave:
      user: postgres
      database: hipages
      password: password
      port: 5432
      host: localhost
      max: 5
      min: 1
      refreshIdle: true
      idleTimeoutMillis: 20000
      # reapIntervalMillis: number;
      # returnToHead?: boolean;
      application_name: test
      # Promise?: PromiseConstructorLik

Context:
  ActiveProfiles: development
