app:
  name: Inceptum Etl
  context:
    - test_1
    - test_2
    - test_3
    - test_4
    - test_5
    - test_6
    - test_7
    - test_8
    - test_9
    - test_10
    - test_11
    - test_12
    - test_13
    - test_14

generalConfig:
  source:
    maxRetries: 3
    timeoutMillis: 5000
  transformer:
    minSuccessPercentage: 1
    timeoutMillis: 5000
  destination:
    maxRetries: 3
    timeoutMillis: 5000
    batchSize: 1

sources:
  adwordsreports:
    maxRetries: 5000
    timeoutMillis: 1
    account: THE_ACCOUNT_NAME
    token: DEVELOPER_TOKEN
    userAgent: YOUR_PROJECT_NAME
    clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
    clientId: ADWORDS_API_CLIENT_ID
    clientSecret: ADWORDS_API_CLIENT_SECRET
    refreshToken: ADWORDS_API_REFRESHTOKEN
    version: v201705
    accountsList:
      - name: ADWORDS_ACOUNT_NAME_1
        id: ADWORDS_ACOUNT_ID_1
      - name: ADWORDS_ACOUNT_NAME_2
        id: ADWORDS_ACOUNT_ID_2
    reportQuery: "SELECT AccountDescriptiveName, AccountTimeZone, CampaignName, CampaignId, AdGroupName, AdGroupId, Criteria, Id, KeywordMatchType, Status, Date, Device, Impressions, Clicks, Conversions, Cost, Ctr, AverageCpc, ConversionRate, CpcBid,  CpcBidSource, QualityScore, HasQualityScore, CreativeQualityScore, CriteriaDestinationUrl, AveragePosition, FirstPageCpc, FirstPositionCpc, TopOfPageCpc, IsNegative, SearchExactMatchImpressionShare, SearchImpressionShare, SearchRankLostImpressionShare, BidType FROM   KEYWORDS_PERFORMANCE_REPORT WHERE  Clicks > 0"
  gatransactions:
    account: hip
    gaViewId: 123456
    clientKey: "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"
    clientEmail: "the.iam.gserviceaccount.com"
  galandingpages:
    account: hip
    gaViewId: 123456
    clientKey: "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"
    clientEmail: "the.iam.gserviceaccount.com"
  mysqldatabykey:
    dbClient: SEO
    sourceOptions:
      tableName: landing_pages_table
      searchColumn: id  
      searchColumnDataType: number
      pk: id  
  adwordsreportshistoricaldata:
    test_12: &adwords
      maxRetries: 5000
      timeoutMillis: 1
      account: THE_ACCOUNT_NAME
      token: DEVELOPER_TOKEN
      userAgent: YOUR_PROJECT_NAME
      clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
      clientId: ADWORDS_API_CLIENT_ID
      clientSecret: ADWORDS_API_CLIENT_SECRET
      refreshToken: ADWORDS_API_REFRESHTOKEN
      version: v201705
      accountsList:
        - name: ADWORDS_ACOUNT_NAME_1
          id: ADWORDS_ACOUNT_ID_1
        - name: ADWORDS_ACOUNT_NAME_2
          id: ADWORDS_ACOUNT_ID_2
      reportQuery: "SELECT AccountDescriptiveName, AccountTimeZone, CampaignName, CampaignId, AdGroupName, AdGroupId, Criteria, Id, KeywordMatchType, Status, Date, Device, Impressions, Clicks, Conversions, Cost, Ctr, AverageCpc, ConversionRate, CpcBid,  CpcBidSource, QualityScore, HasQualityScore, CreativeQualityScore, CriteriaDestinationUrl, AveragePosition, FirstPageCpc, FirstPositionCpc, TopOfPageCpc, IsNegative, SearchExactMatchImpressionShare, SearchImpressionShare, SearchRankLostImpressionShare, BidType FROM   KEYWORDS_PERFORMANCE_REPORT WHERE  Clicks > 0"

transformers:
  splitadwordscampaign:
    fixedFields:
      app_code: HIP
      source_name: Adwords
      source_account: hip
      record_created_date: '2017-08-23 10:30:45'
      source_time_zone: '(GMT+10:00) Eastern Time - Melbourne, Sydney'
    fieldsRequiringMapping:
      keyword_placement: keyword__placement
  simplecopy:
    available: true
  smartfieldmapping:
    tempDirectory: .
    regexPath: './regex.json'
    bucket: 'bucketName'
    fieldsMapping:
      app_code: 
        action: add
        field: account
      source_name:
        action: add
        value: Google Analytics
      source_time_zone:
        action: add
        value: '(GMT+10:00) Eastern Time - Melbourne, Sydney'
      source_account:
        action: replace
        field: account
      record_created_date:
        action: replace
        field: created_by_date
      landing_content_group5:
        action: regexAdd
        field: landing_page_path
  fieldsmapping:
    fixedFields:
      app_code: HIP
      source_name: Adwords
      source_account: hip
      record_created_date: '2017-08-23 10:30:45'
      source_time_zone: '(GMT+10:00) Eastern Time - Melbourne, Sydney'
    mappedFields:
      report_date: report_date
      medium: medium
      source: source
      landing_page_path: landingPagePath
      device_category: deviceCategory
      region: region
      campaign: campaign
      ad_group: adGroup
      landing_content_group: landingContentGroup5
      sessions: sessions
      percent_new_sessions: percentNewSessions
      organic_searches: organicSearches
      goal_1_completions: goal1Completions
      goal_15_completions: goal15Completions
      pageviews: pageviews

destinations:
  csvfile:
    directory: .
    fileName: akp
    cleanUpDirectory : false
  jsonfile:
    directory: .
    fileName: akp
    cleanUpDirectory : false
  redshift:
    dbClient: dwRedshift
    bucket: bucket/path
    tempDirectory: .
    tableCopyName: copy.fact_keywords_performance
    tableName: dwh.fact_keywords_performance
    bulkDeleteMatchFields: 
      - account 
      - report_date
    iamRole:
  s3bucket:
    fileType: json
    bucket: bucket/path
    tempDirectory: .
    fileName: akp

savepoints:
  mysql:
    dbClient: EtlSavePoint
  static:
    savepoint: '{"startDate":"20170731","endDate":"20170801","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

etls:
  test_1: 
    source:
      type: adwordsreports
      maxRetries: 5000
      timeoutMillis: 1
      account: THE_ACCOUNT_NAME
      token: DEVELOPER_TOKEN
      userAgent: YOUR_PROJECT_NAME
      clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
      clientId: ADWORDS_API_CLIENT_ID
      clientSecret: ADWORDS_API_CLIENT_SECRET
      refreshToken: ADWORDS_API_REFRESHTOKEN
      version: v201705
      accountsList:
        - name: ADWORDS_ACOUNT_NAME_1
          id: ADWORDS_ACOUNT_ID_1
        - name: ADWORDS_ACOUNT_NAME_2
          id: ADWORDS_ACOUNT_ID_2
      reportQuery: "SELECT AccountDescriptiveName, AccountTimeZone, CampaignName, CampaignId, AdGroupName, AdGroupId, Criteria, Id, KeywordMatchType, Status, Date, Device, Impressions, Clicks, Conversions, Cost, Ctr, AverageCpc, ConversionRate, CpcBid,  CpcBidSource, QualityScore, HasQualityScore, CreativeQualityScore, CriteriaDestinationUrl, AveragePosition, FirstPageCpc, FirstPositionCpc, TopOfPageCpc, IsNegative, SearchExactMatchImpressionShare, SearchImpressionShare, SearchRankLostImpressionShare, BidType FROM   KEYWORDS_PERFORMANCE_REPORT WHERE  Clicks > 0"
    transformer:
      type: splitadwordscampaign
      fixedFields:
        app_code: HIP
        source_name: Adwords
        source_account: hip
        record_created_date: '2017-08-23 10:30:45'
        source_time_zone: '(GMT+10:00) Eastern Time - Melbourne, Sydney'
      fieldsRequiringMapping:
        keyword_placement: keyword__placement
    destination:
      type: csvfile
      directory: .
      fileName: akp
      cleanUpDirectory : false
    savepoint:
      type: mysql
      dbClient: EtlSavePoint

  test_2: 
    source:
      type: adwordsreports
      maxRetries: 5000
      timeoutMillis: 1
      account: THE_ACCOUNT_NAME
      token: DEVELOPER_TOKEN
      userAgent: YOUR_PROJECT_NAME
      clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
      clientId: ADWORDS_API_CLIENT_ID
      clientSecret: ADWORDS_API_CLIENT_SECRET
      refreshToken: ADWORDS_API_REFRESHTOKEN
      version: v201705
      accountsList:
        - name: ADWORDS_ACOUNT_NAME_1
          id: ADWORDS_ACOUNT_ID_1
        - name: ADWORDS_ACOUNT_NAME_2
          id: ADWORDS_ACOUNT_ID_2
      reportQuery: "SELECT AccountDescriptiveName, CampaignName, CampaignId, AdGroupName, AdGroupId, CriteriaParameters, CriteriaId, KeywordMatchType, AdFormat, CreativeId, Device, Date, GclId, Clicks, ClickType, ExternalCustomerId, Page, Slot FROM   CLICK_PERFORMANCE_REPORT"
    transformer:
      type: simplecopy
      available: true
    destination:
      type: s3bucket
      fileType: json
      bucket: bucket/path
      tempDirectory: .
      fileName: akp
    savepoint:
      type: static
      savepoint: '{"startDate":"20170731","endDate":"20170801","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

  test_3:
    transformer:
      type: simplecopy
      available: true
    destination:
      type: jsonfile
      directory: .
      fileName: akp
      cleanUpDirectory : false
    savepoint:
      type: static
      savepoint: '{"startDate":"20170731","endDate":"20170801","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

  test_4:
    transformer:
      type: simplecopy
      available: true
    destination:
      type: redshift
      dbClient: dwRedshift
      bucket: bucket/path
      tempDirectory: .
      tableCopyName: copy.fact_keywords_performance
      tableName: dwh.fact_keywords_performance
      bulkDeleteMatchFields: 
        - account 
        - report_date
      iamRole:
    savepoint:
      type: static
      savepoint: '{"startDate":"20170731","endDate":"20170801","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

  test_5:
    source:
      type: gatransactions
      account: hip
      gaViewId: 123456
      clientKey: "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"
      clientEmail: "the.iam.gserviceaccount.com"
    savepoint:
      type: static
      savepoint: '{"startDate":"2017-08-10","endDate":"2017-08-12","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

  test_6:
    source:
      type: galandingpages
      account: hip
      gaViewId: 123456
      clientKey: "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"
      clientEmail: "the.iam.gserviceaccount.com"
    savepoint:
      type: static
      savepoint: '{"startDate":"2017-08-11","endDate":"2017-08-12","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

  test_7:
    source:
      type: extendedsource
      param: value_source
    transformer:
      type: extendedtransformer
      param: value_transformer
    destination:
      type: extendeddestination
      param: value_destination
    savepoint:
      type: extendedsavepoint
      param: value_savepoint

  test_8:
    source:
      type: mysqldatabykey
      dbClient: SEO
      sourceOptions:
        tableName: landing_pages_table
        searchColumn: id  
        searchColumnDataType: number
        pk: id  
    transformer:
      type: smartfieldmapping
      tempDirectory: .
      regexPath: './regex.json'
      bucket: 'bucketName'
      fieldsMapping:
        app_code: 
          action: add
          field: account
        source_name:
          action: add
          value: Google Analytics
        source_time_zone:
          action: add
          value: '(GMT+10:00) Eastern Time - Melbourne, Sydney'
        source_account:
          action: replace
          field: account
        record_created_date:
          action: replace
          field: created_by_date
        landing_content_group5:
          action: regexAdd
          field: landing_page_path
    savepoint:
      type: static
      savepoint: '{"columnStartValue":48172195,"columnEndValue":48172196,"batchSize":10,"currentBatch":0,"totalBatches":0,"currentDate":"2017-08-28T17:42:41.349Z"}'

  test_9:
    source:
      type: mysqldatabykey
      dbClient: GA
      sourceOptions:
        tableName: job_table
        searchColumn: job_id  
        searchColumnDataType: number
        pk: job_id  
    transformer:
      type: smartfieldmapping
      tempDirectory: .
      regexPath: './regex.json'
      bucket: 'bucketName'
      fieldsMapping:
        app_code: 
          action: add
          field: account
        source_name:
          action: add
          value: Google Analytics
        source_time_zone:
          action: add
          value: null
        report_date:
          action: add
          field: created_by_date
        source_account:
          action: replace
          field: account
        record_created_date:
          action: replace
          field: created_by_date
        landing_content_group5:
          action: regexAdd
          field: landing_page_path
    savepoint:
      type: static
      savepoint: '{"columnStartValue":3656974,"columnEndValue":3656975,"batchSize":10,"currentBatch":0,"totalBatches":1,"currentDate":"2017-08-28T17:42:41.349Z"}'

  test_10:
    transformer:
      type: fieldsmapping
      fixedFields:
        app_code: HIP
        source_name: Adwords
        source_account: hip
        record_created_date: '2017-08-23 10:30:45'
        source_time_zone: '(GMT+10:00) Eastern Time - Melbourne, Sydney'
      mappedFields:
        report_date: report_date
        medium: medium
        source: source
        landing_page_path: landingPagePath
        device_category: deviceCategory
        region: region
        campaign: campaign
        ad_group: adGroup
        landing_content_group: landingContentGroup5
        sessions: sessions
        percent_new_sessions: percentNewSessions
        organic_searches: organicSearches
        goal_1_completions: goal1Completions
        goal_15_completions: goal15Completions
        pageviews: pageviews

  test_11:
    transformer:
      type: fieldsmapping
      fixedFields:
      mappedFields:
        report_date: report_date
        medium: medium
        source: source
        landing_page_path: landingPagePath
        device_category: deviceCategory
        region: region
        campaign: campaign
        ad_group: adGroup
        landing_content_group: landingContentGroup5
        sessions: sessions
        percent_new_sessions: percentNewSessions
        organic_searches: organicSearches
        goal_1_completions: goal1Completions
        goal_15_completions: goal15Completions
        pageviews: pageviews

  test_12:
    source:
      type: adwordsreportshistoricaldata
      maxRetries: 5000
      timeoutMillis: 1
      account: THE_ACCOUNT_NAME
      token: DEVELOPER_TOKEN
      userAgent: YOUR_PROJECT_NAME
      clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
      clientId: ADWORDS_API_CLIENT_ID
      clientSecret: ADWORDS_API_CLIENT_SECRET
      refreshToken: ADWORDS_API_REFRESHTOKEN
      version: v201705
      accountsList:
        - name: ADWORDS_ACOUNT_NAME_1
          id: ADWORDS_ACOUNT_ID_1
        - name: ADWORDS_ACOUNT_NAME_2
          id: ADWORDS_ACOUNT_ID_2
      reportQuery: "SELECT AccountDescriptiveName, AccountTimeZone, CampaignName, CampaignId, AdGroupName, AdGroupId, Criteria, Id, KeywordMatchType, Status, Date, Device, Impressions, Clicks, Conversions, Cost, Ctr, AverageCpc, ConversionRate, CpcBid,  CpcBidSource, QualityScore, HasQualityScore, CreativeQualityScore, CriteriaDestinationUrl, AveragePosition, FirstPageCpc, FirstPositionCpc, TopOfPageCpc, IsNegative, SearchExactMatchImpressionShare, SearchImpressionShare, SearchRankLostImpressionShare, BidType FROM   KEYWORDS_PERFORMANCE_REPORT WHERE  Clicks > 0"
    savepoint:
      type: static
      savepoint: '{"startDate":"20170901","endDate":"20170910","paceAmount":1,"paceTime":"months","finalDate":"20170701","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

  test_13:
    source:
      type: readcsvfile
      fileName: ./this/is/an/example.txt
      fileHasHeader: False
      headers:
        - header_1
        - header_2
        - header_3
    savepoint:
      type: static
      savepoint: '{"blockSize":2,"line":0,"batchNumber":0}'

  test_14:
    source:
      type: adwordsreportlargefile
      maxRetries: 5000
      timeoutMillis: 1
      tempDirectory: ./tmp
      account: THE_ACCOUNT_NAME
      token: DEVELOPER_TOKEN
      userAgent: YOUR_PROJECT_NAME
      clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
      clientId: ADWORDS_API_CLIENT_ID
      clientSecret: ADWORDS_API_CLIENT_SECRET
      refreshToken: ADWORDS_API_REFRESHTOKEN
      version: v201705
      reportQuery: "SELECT QueryMatchTypeWithVariant, Query, CampaignId, CampaignName, AdGroupId, AdGroupName, Clicks, Impressions, Ctr, AverageCpc, Cost,AveragePosition, Conversions, CostPerConversion, ConversionRate, AllConversions, ViewThroughConversions FROM SEARCH_QUERY_PERFORMANCE_REPORT "
    savepoint:
      type: static
      savepoint: '{"startDate":"20170731","endDate":"20170801","currentDate":"2017-08-01T01:14:37.995Z","blockSize":2,"line":0,"batchNumber":0}'

mysql:
  EtlSavePoint:    
    master:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
    slave:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
  GA:    
    master:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
    slave:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
      
postgres:
  dwRedshift:
    master:
      user: postgres
      database: hipages
      password: password
      port: 5432
      host: localhost
      max: 5
      min: 1
      refreshIdle: true
      idleTimeoutMillis: 20000
      application_name: test
    slave:
      user: postgres
      database: hipages
      password: password
      port: 5432
      host: localhost
      max: 5
      min: 1
      refreshIdle: true
      idleTimeoutMillis: 20000
      application_name: test

logging:
  streams:
    console:
      type: console
    myredis:
      type: redis
    mainLogFile:
      type: file
      path: main.log
  loggers:
    - name: ROOT
      streams:
        console: fatal
    - name: ioc/
      streams:
        console: debug
    - name: mysql/
      streams:
        console: debug
