app:
  name: Inceptum Etl
  context:
    - test_1
    - test_2
    - test_3
    - test_4
    - test_5
    - test_6

etlOptions:
  test_1: &generalOptions
    source:
      maxRetries: 3
      timeoutMillis: 5000
    transformers:
      minSuccessPercentage: 1
      timeoutMillis: 5000
    destinations:
      maxRetries: 3
      timeoutMillis: 5000
      batchSize: 1
  test_2:
    <<: *generalOptions
  test_3:
    <<: *generalOptions
  test_4:
    <<: *generalOptions
  test_5:
    <<: *generalOptions
  test_6:
    <<: *generalOptions

sources:
  adwordsclicks:
    adwords: &adwords
      maxRetries: 5000
      timeoutMillis: 1
      account: THE_ACCOUNT_NAME
      token: DEVELOPER_TOKEN
      userAgent: YOUR_PROJECT_NAME
      clientCustomerId: ADWORDS_MCC_ACCOUNT_ID
      clientId: ADWORDS_API_CLIENT_ID
      clientSecret: ADWORDS_API_CLIENT_SECRET
      refreshToken: ADWORDS_API_REFRESHTOKEN
      version: v201705
      accountsList:
        - name: ADWORDS_ACOUNT_NAME_1
          id: ADWORDS_ACOUNT_ID_1
        - name: ADWORDS_ACOUNT_NAME_2
          id: ADWORDS_ACOUNT_ID_2
    test_1: 
      <<: *adwords
  adwordskeywords:
    test_2: 
      <<: *adwords
  gatransactions:
    test_5:
      account: hip
      gaViewId: 123456
      clientKey: "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"
      clientEmail: "the.iam.gserviceaccount.com"
  galandingpages:
    test_6:
      account: hip
      gaViewId: 123456
      clientKey: "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"
      clientEmail: "the.iam.gserviceaccount.com"

transformers:
  splitadwordscampaign:
    test_1:
      available: true
  simplecopy:
    test_2:
      available: true
  gatransactions:
    test_3:
      fieldsMapping: 
        job_id: job_id
        partner_job_id: partner_job_id
        transaction_id: transactionId
        campaign: campaign
        source: source
        ad_group: adGroup
        medium: medium
        keyword: keyword
        landing_page_path: landingPagePath
        ad_matched_query: adMatchedQuery
        device_category: deviceCategory
        browser: browser
        browser_version: browserVersion
        browser_size: browserSize
  galandingpages:
    test_4:
      dbClient: EtlSavePoint
      fieldsMapping: 
        source_account: source_account
        report_date: report_date
        page: page
        base: base
        category: category
        category_parent_id: category_parent_id
        medium: medium
        source: source
        landing_page_path: landingPagePath
        device_category: deviceCategory
        region: region
        campaign: campaign
        ad_group: adGroup
        landing_content_group5: landingContentGroup5
        sessions: sessions
        percent_new_sessions: percentNewSessions
        organic_searches: organicSearches
        goal1_completions: goal1Completions
        goal15_completions: goal15Completions
        pageviews: pageviews
        record_created_date: record_created_date

destinations:
  csvfile:
    test_1:
      directory: /temp
      fileName: akp
      cleanUpDirectory : false
  jsonfile:
    test_3:
      directory: /temp
      fileName: akp
      cleanUpDirectory : false
  redshift:
    test_4: 
      dbClient: dwRedshift
      bucket: bucket/path
      tempDirectory: /temp
      tableCopyName: copy.fact_keywords_performance
      tableName: dwh.fact_keywords_performance
      bulkDeleteMatchFields: 
        - account 
        - report_date
      iamRole:
  s3bucket:
    test_2: 
      fileType: json
      bucket: bucket/path
      tempDirectory: /temp
      fileName: akp

savepoints:
  mysql:
    test_1: 
      dbClient: EtlSavePoint
  static:
    test_2: 
      savepoint: '{"startDate":"20170731","endDate":"20170801","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'
    test_3:
      savepoint: '{"startDate":"20170731","endDate":"20170801","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'
    test_4:
      savepoint: '{"startDate":"20170731","endDate":"20170801","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'
    test_5: 
      savepoint: '{"startDate":"2017-08-10","endDate":"2017-08-12","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'
    test_6: 
      savepoint: '{"startDate":"2017-08-11","endDate":"2017-08-12","currentBatch":1,"totalBatches":1,"currentDate":"2017-08-01T01:14:37.995Z"}'

mysql:
  EtlSavePoint:    
    master:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
    slave:
      host: localhost
      port: 3306
      user: root
      password:
      database: testDb
      charset: utf8
      connectionLimit: 10
      
postgres:
  dwRedshift:
    master:
      user: postgres
      database: hipages
      password: password
      port: 5432
      host: localhost
      max: 5
      min: 1
      refreshIdle: true
      idleTimeoutMillis: 20000
      application_name: test
    slave:
      user: postgres
      database: hipages
      password: password
      port: 5432
      host: localhost
      max: 5
      min: 1
      refreshIdle: true
      idleTimeoutMillis: 20000
      application_name: test

logging:
  streams:
    console:
      type: console
    myredis:
      type: redis
    mainLogFile:
      type: file
      path: main.log
  loggers:
    - name: ROOT
      streams:
        console: debug
    - name: ioc/
      streams:
        console: debug
    - name: mysql/
      streams:
        console: debug

Context:
  ActiveProfiles: development
